[package]
name = "budget"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0"
authors = ["Shayne Stewart"]
readme = "README.md"
repository = "https://github.com/shwcsmack/budget/"
description = "A budget app made from scratch in rust"

[dependencies]
dialoguer = "0.10.1"